"""adding user_id to exercise table

Revision ID: 28f303f9dd2b
Revises: fb7f5b36d90f
Create Date: 2022-08-08 21:42:34.366683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f303f9dd2b'
down_revision = 'fb7f5b36d90f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'exercises', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'owner_id')
    # ### end Alembic commands ###
