"""added new table exercise

Revision ID: a6802b5ea3f0
Revises: 4f009b4d27e3
Create Date: 2022-08-05 20:35:36.629266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6802b5ea3f0'
down_revision = '4f009b4d27e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('list_index', sa.Integer(), nullable=False),
    sa.Column('rep_count', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('weight_type', sa.String(), nullable=False),
    sa.Column('worksession_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['worksession_id'], ['worksessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercises')
    # ### end Alembic commands ###
