"""updated exercise table, weight column to float

Revision ID: fb7f5b36d90f
Revises: a6802b5ea3f0
Create Date: 2022-08-06 21:32:24.545011

"""
from alembic import op
import sqlalchemy as sa
# from sqlalchemy import Float

# revision identifiers, used by Alembic.
revision = 'fb7f5b36d90f'
down_revision = 'a6802b5ea3f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.alter_column('exercises', 'weight', type_=sa.Float())
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    op.alter_column('exercises', 'weight', type_=sa.Integer())


    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
